// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXMbjQ-vHKCBwHI2vAU05eRBsLWfBjZek',
    appId: '1:547351776280:web:a722413f888d5a4286076d',
    messagingSenderId: '547351776280',
    projectId: 'uwulesson',
    authDomain: 'uwulesson.firebaseapp.com',
    storageBucket: 'uwulesson.appspot.com',
    measurementId: 'G-7MMMR6VXSD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnYDtppXs--j7GpnxjtKJGYllCCLI1NDA',
    appId: '1:547351776280:android:5ce521df5b65d4c386076d',
    messagingSenderId: '547351776280',
    projectId: 'uwulesson',
    storageBucket: 'uwulesson.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoXjXT92bZ5UxKYI104zEM3nua0vp9Zrg',
    appId: '1:547351776280:ios:568136c672f991fc86076d',
    messagingSenderId: '547351776280',
    projectId: 'uwulesson',
    storageBucket: 'uwulesson.appspot.com',
    iosClientId: '547351776280-soma72k2p5u5d3t16v3p52j57kaooqi1.apps.googleusercontent.com',
    iosBundleId: 'com.aaostudios.uwulesson',
  );
}
